version: '3.7'
services:
  pydm:
    image: lnls/pydm
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    network_mode: "host"
    dns:
      - 10.0.0.71
      - 10.0.0.72
    environment:
      - DISPLAY
      - EPICS_CA_ADDR_LIST=10.128.1.255
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
